# Generated by Django 3.1.6 on 2021-05-21 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='watch_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.watchtype', verbose_name='Тип часов'),
        ),
        migrations.AddField(
            model_name='product',
            name='waterproof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.waterproof', verbose_name='Водонепроницаемость'),
        ),
        migrations.AddField(
            model_name='product',
            name='zip_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zip_material', to='prod.material', verbose_name='Тип застёжки'),
        ),
        migrations.AddField(
            model_name='product',
            name='zip_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.ziptype', verbose_name='Материал застёжки'),
        ),
        migrations.AddField(
            model_name='images',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.product'),
        ),
    ]
