# Generated by Django 3.1.3 on 2020-12-17 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0004_auto_20201217_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.ForeignKey(blank=True, default='---', null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.sex', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Пол'),
        ),
    ]
